// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnNfmlOUFdwtO8NrsQbyfG3-B8nj-B5-0',
    appId: '1:796245605804:web:a5a68a6744023c5ef78e09',
    messagingSenderId: '796245605804',
    projectId: 'music-services-app-dcbdd',
    authDomain: 'music-services-app-dcbdd.firebaseapp.com',
    storageBucket: 'music-services-app-dcbdd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAGpSC8y1IeY9HL8hl6SSbjJ_kqbs1rU',
    appId: '1:796245605804:android:129911d738048202f78e09',
    messagingSenderId: '796245605804',
    projectId: 'music-services-app-dcbdd',
    storageBucket: 'music-services-app-dcbdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzkFPsSap3T1E6k4oE6_EI3dmqDlDzIA',
    appId: '1:796245605804:ios:6d0b706074cef365f78e09',
    messagingSenderId: '796245605804',
    projectId: 'music-services-app-dcbdd',
    storageBucket: 'music-services-app-dcbdd.firebasestorage.app',
    iosBundleId: 'com.example.musicServicesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzkFPsSap3T1E6k4oE6_EI3dmqDlDzIA',
    appId: '1:796245605804:ios:6d0b706074cef365f78e09',
    messagingSenderId: '796245605804',
    projectId: 'music-services-app-dcbdd',
    storageBucket: 'music-services-app-dcbdd.firebasestorage.app',
    iosBundleId: 'com.example.musicServicesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnNfmlOUFdwtO8NrsQbyfG3-B8nj-B5-0',
    appId: '1:796245605804:web:9ddbc9d817ea86eff78e09',
    messagingSenderId: '796245605804',
    projectId: 'music-services-app-dcbdd',
    authDomain: 'music-services-app-dcbdd.firebaseapp.com',
    storageBucket: 'music-services-app-dcbdd.firebasestorage.app',
  );
}
